#!/usr/bin/env python3
"""Regenerate the E5 RAG comparison table from archived, rescored JSONL."""
from __future__ import annotations
import argparse, json
from collections import defaultdict
from pathlib import Path

ORDER = ["temporal", "observer", "counterfactual", "scope", "source_conflict", "modality", "hidden_premise"]
LABEL = {"temporal":"Temporal", "observer":"Observer", "counterfactual":"Counterfact.", "scope":"Scope", "source_conflict":"Source confl.", "modality":"Modality", "hidden_premise":"Hidden prem."}

def read(paths, wanted, categories):
    values = defaultdict(list); seen=set()
    for path in paths:
        for line in path.read_text().splitlines():
            if not line.strip(): continue
            r=json.loads(line); key=(r.get("model"), r.get("condition"), r.get("id"))
            if r.get("error") is not None or r.get("condition") not in wanted or key in seen: continue
            seen.add(key); values[(categories[r["id"]], r["condition"])].append(int(r["correct"]))
    return values

def pct(xs): return 100 * sum(xs) / len(xs)
def main():
    p=argparse.ArgumentParser(); p.add_argument("--rag-dir",default="paper/results/raw_rag"); p.add_argument("--full-dir",default="paper/results/raw"); p.add_argument("--data",default="paper/data/situationcatch_llm_sample.jsonl"); p.add_argument("--out",default="paper/section/tables/e5_rag_table.tex"); a=p.parse_args()
    categories={r["id"]:r["category"] for r in map(json.loads, Path(a.data).read_text().splitlines())}
    rag=read(sorted(Path(a.rag_dir).glob("e5_gemini_*.jsonl")), {"direct"}, categories)
    full=read(sorted(Path(a.full_dir).glob("e5_gemini_*.jsonl")), {"structured","situation"}, categories)
    rows=[]; totals={c:[] for c in ("direct","structured","situation")}
    for cat in ORDER:
        vals={"direct":rag[(cat,"direct")], "structured":full[(cat,"structured")], "situation":full[(cat,"situation")]}
        if any(len(x)!=90 for x in vals.values()): raise SystemExit(f"incomplete {cat}: "+str({k:len(v) for k,v in vals.items()}))
        for c,x in vals.items(): totals[c]+=x
        r,s,t=map(lambda c:pct(vals[c]), ("direct","structured","situation"))
        rows.append(f"{LABEL[cat]} & {r:.1f} & {s:.1f} & {t:.1f} & {t-r:+.1f} \\\\")
    r,s,t=map(lambda c:pct(totals[c]), ("direct","structured","situation"))
    tex=r'''% Generated by code/make_rag_table.py from archived rescored raw; do not edit.
\begin{table}[t]
\caption{Retrieval-augmented (RAG) baseline versus full-evidence prompting, mean accuracy over the three Gemini models on the $n=210$ sample. RAG answers from the top-3 lexically retrieved claims (plain text); Structured and Situation see all claims. On the two categories that most require reasoning over the applicability state -- temporal validity and observer knowledge -- the full-state conditions beat RAG; elsewhere a focused RAG is as good or better, and its aggregate lead is driven by clarification (hidden premise), where the plain prompt elicits the CLARIFY token more readily.}
\label{tab:e5-rag}
\centering\small\setlength{\tabcolsep}{5pt}%
\begin{tabular}{lrrrr}
\toprule
Category & RAG (top-3) & Structured & Situation & Sit.$-$RAG \\
\midrule
'''+"\n".join(rows)+f'''\n\\midrule
Overall & {r:.1f} & {s:.1f} & {t:.1f} & {t-r:+.1f} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
'''
    Path(a.out).write_text(tex); print(f"Wrote audited 3 x 210 comparison to {a.out}")
if __name__=="__main__": main()
