#!/usr/bin/env python3
"""Regenerate the E5 baseline comparison table from archived, rescored JSONL."""
from __future__ import annotations
import argparse, json
from collections import defaultdict
from pathlib import Path

ORDER = ["temporal", "observer", "counterfactual", "scope", "source_conflict", "modality", "hidden_premise"]
LABEL = {"temporal":"Temporal", "observer":"Observer", "counterfactual":"Counterfact.", "scope":"Scope", "source_conflict":"Source confl.", "modality":"Modality", "hidden_premise":"Hidden prem."}
# Column order: retrieval baseline, two full-evidence prompts, tool-using agent.
COLS = ["direct", "structured", "situation", "agent"]
HEAD = {"direct":"RAG (top-3)", "structured":"Structured", "situation":"Situation", "agent":"Agent"}

def read(paths, wanted, categories):
    values = defaultdict(list); seen=set()
    for path in paths:
        for line in path.read_text().splitlines():
            if not line.strip(): continue
            r=json.loads(line); key=(r.get("model"), r.get("condition"), r.get("id"))
            if r.get("error") is not None or r.get("condition") not in wanted or key in seen: continue
            seen.add(key); values[(categories[r["id"]], r["condition"])].append(int(r["correct"]))
    return values

def pct(xs): return 100 * sum(xs) / len(xs)
def main():
    p=argparse.ArgumentParser()
    p.add_argument("--rag-dir",default="paper/results/raw_rag")
    p.add_argument("--full-dir",default="paper/results/raw")
    p.add_argument("--agent-dir",default="paper/results/raw_agent")
    p.add_argument("--data",default="paper/data/situationcatch_llm_sample.jsonl")
    p.add_argument("--out",default="paper/section/tables/e5_rag_table.tex")
    a=p.parse_args()
    categories={r["id"]:r["category"] for r in map(json.loads, Path(a.data).read_text().splitlines())}
    rag=read(sorted(Path(a.rag_dir).glob("e5_gemini_*.jsonl")), {"direct"}, categories)
    full=read(sorted(Path(a.full_dir).glob("e5_gemini_*.jsonl")), {"structured","situation"}, categories)
    agent=read(sorted(Path(a.agent_dir).glob("agent_gemini_*.jsonl")), {"agent"}, categories)
    def get(cat, cond):
        return {"direct":rag, "structured":full, "situation":full, "agent":agent}[cond][(cat, cond)]
    rows=[]; totals={c:[] for c in COLS}
    for cat in ORDER:
        vals={c:get(cat,c) for c in COLS}
        if any(len(x)!=90 for x in vals.values()): raise SystemExit(f"incomplete {cat}: "+str({k:len(v) for k,v in vals.items()}))
        for c,x in vals.items(): totals[c]+=x
        cells=" & ".join(f"{pct(vals[c]):.1f}" for c in COLS)
        rows.append(f"{LABEL[cat]} & {cells} \\\\")
    ov=" & ".join(f"{pct(totals[c]):.1f}" for c in COLS)
    header=" & ".join(HEAD[c] for c in COLS)
    tex=(r"""% Generated by code/make_rag_table.py from archived rescored raw; do not edit.
\begin{table}[t]
\caption{Retrieval-augmented (RAG), full-evidence prompting, and a tool-using agent, mean accuracy over the three Gemini models on the $n=210$ sample. RAG answers from the top-3 lexically retrieved claims; Structured and Situation see all claims; Agent may issue its own search queries over the item's claims before answering. On the two categories that most require reasoning over the applicability state -- temporal validity and observer knowledge -- the full-evidence conditions beat both retrieval and the agent, while none of the retrieval-, prompt-, or tool-based interventions dominates overall.}
\label{tab:e5-rag}
\centering\small\setlength{\tabcolsep}{5pt}%
\begin{tabular}{l"""+"r"*len(COLS)+r"""}
\toprule
Category & """+header+r""" \\
\midrule
"""+"\n".join(rows)+r"""
\midrule
Overall & """+ov+r""" \\
\bottomrule
\end{tabular}
\end{table}
""")
    Path(a.out).write_text(tex); print(f"Wrote audited 3 x 210 comparison (incl. agent) to {a.out}")
if __name__=="__main__": main()
