#!/usr/bin/env python3
"""Turn the E5 multi-model summary CSV into the manuscript's E5 results table.

Reads ``paper/results/multimodel_summary.csv`` (written by
``summarize_multimodel.py``) and emits a LaTeX ``table`` to
``paper/section/tables/e5_multimodel_table.tex`` for ``\\input`` from the
Results section. It also prints the situation-on-versus-off contrast that the
E5 manifest defines as the primary quantity.

Integrity guard: this generator never fabricates numbers. Rows from the offline
``mock`` provider and rows with zero successful calls are dropped. If no real
model rows survive, it writes a clearly-labelled PENDING placeholder (a LaTeX
comment plus a visible "awaiting E5 run" note) instead of a results table, and
exits 0 so it can sit in the build pipeline before the paid run has happened.

Usage:
    python code/make_e5_table.py
    python code/make_e5_table.py --summary paper/results/multimodel_summary.csv \
        --out paper/section/tables/e5_multimodel_table.tex
"""
from __future__ import annotations
import argparse
import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Column order and short headers for the manuscript table.
CONDITIONS = [
    ("direct", "Direct"),
    ("chain_of_thought", "CoT"),
    ("structured", "Struct."),
    ("date_context", "Date"),
    ("self_reflection", "Self-ref."),
    ("situation", "Situation"),
]
# Non-situation baselines the "situation" condition is contrasted against.
BASELINES = [c for c, _ in CONDITIONS if c != "situation"]

PLACEHOLDER = r"""% E5 multi-model table -- PENDING.
% No real model rows were found in the summary CSV yet (only mock/empty data).
% Run:  python code/run_e5.py        (needs OPENROUTER_API_KEY with credits)
% then: python code/make_e5_table.py  to regenerate this file with real numbers.
\begin{table}[t]
\caption{E5 multi-model situation-intervention results \emph{(pending execution;
no frontier-model responses are included in this build)}. Regenerated
automatically from \texttt{paper/results/multimodel\_summary.csv} once
\texttt{code/run\_e5.py} has produced real responses.}
\label{tab:e5-multimodel}
\centering\small
\begin{tabular}{l}
\toprule
Awaiting E5 execution --- see \texttt{code/experiment\_manifest.e5.json}. \\
\bottomrule
\end{tabular}
\end{table}
"""


def load_rows(path: Path):
    """Return {(model): {condition: (accuracy, n_success)}} for real rows only."""
    by_model: dict[str, dict[str, tuple[float, int]]] = defaultdict(dict)
    dropped = 0
    with path.open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            provider = (r.get("provider") or "").strip().lower()
            n_success = int(r.get("n_success") or 0)
            if provider == "mock" or n_success == 0:
                dropped += 1
                continue
            model = r["model"]
            by_model[model][r["condition"]] = (float(r["accuracy"]), n_success)
    return by_model, dropped


def fmt_pct(value: float) -> str:
    return f"{100 * value:.1f}"


def build_table(by_model) -> str:
    header_cells = " & ".join(short for _, short in CONDITIONS)
    lines = [
        r"% E5 multi-model table -- generated by code/make_e5_table.py from "
        r"paper/results/multimodel_summary.csv. Do not edit by hand.",
        r"\begin{table}[t]",
        r"\caption{E5 multi-model situation-intervention accuracy on the "
        r"rendered SituationCatch-Bench sample, under matched evidence and token "
        r"budgets (temperature 0). $\Delta$ is the situation condition minus the "
        r"best non-situational prompt for the same model. Numbers are read "
        r"directly from archived raw responses; failed calls are excluded and "
        r"reported as $n$.}",
        r"\label{tab:e5-multimodel}",
        r"\centering\small",
        r"\setlength{\tabcolsep}{4pt}%",
        r"\begin{tabular}{l" + "r" * len(CONDITIONS) + "r}",
        r"\toprule",
        f"Model & {header_cells} & $\\Delta$ \\\\",
        r"\midrule",
    ]
    for model in sorted(by_model):
        conds = by_model[model]
        cells = []
        for cond, _ in CONDITIONS:
            cells.append(fmt_pct(conds[cond][0]) if cond in conds else r"\textemdash")
        # situation-on-versus-off delta
        base_vals = [conds[b][0] for b in BASELINES if b in conds]
        if "situation" in conds and base_vals:
            delta = 100 * (conds["situation"][0] - max(base_vals))
            delta_str = f"{delta:+.1f}"
        else:
            delta_str = r"\textemdash"
        safe_model = model.replace("_", r"\_")
        lines.append(f"{safe_model} & " + " & ".join(cells) + f" & {delta_str} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--summary", default="paper/results/multimodel_summary.csv")
    p.add_argument("--out", default="paper/section/tables/e5_multimodel_table.tex")
    args = p.parse_args()

    summary = ROOT / args.summary
    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)

    if not summary.exists():
        out.write_text(PLACEHOLDER, encoding="utf-8")
        print(f"No summary at {args.summary}; wrote PENDING placeholder to {args.out}.")
        return 0

    by_model, dropped = load_rows(summary)
    if not by_model:
        out.write_text(PLACEHOLDER, encoding="utf-8")
        print(f"Summary has no real model rows ({dropped} mock/empty rows "
              f"dropped); wrote PENDING placeholder to {args.out}.")
        return 0

    out.write_text(build_table(by_model), encoding="utf-8")
    print(f"Wrote E5 table for {len(by_model)} model(s) to {args.out} "
          f"({dropped} mock/empty rows dropped).")
    # Console view of the primary contrast.
    print("\nSituation-on-versus-off (situation minus best baseline):")
    for model in sorted(by_model):
        conds = by_model[model]
        base = [conds[b][0] for b in BASELINES if b in conds]
        if "situation" in conds and base:
            d = 100 * (conds["situation"][0] - max(base))
            print(f"  {model:40s} situation={fmt_pct(conds['situation'][0])}%  "
                  f"best_baseline={fmt_pct(max(base))}%  delta={d:+.1f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
